name: Read Git Secret Values
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.ADMIN_USERNAME }}  ${{ secrets.ADMIN_PASSWORD }}"