# https://crontab.cronhub.io/
# https://sqatools.in/github-actions-fundamentals-for-beginners/

name: workflow dispatch - Manual Release
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

      message:
        description: 'Deployment Started'
        required: true
        default: 'Good morning, team!'
        type: string

jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"

  deploy2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"

  deploy3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"

  deploy4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"

  TriggerJob:
    uses: ./.github/workflows/onworkflowcall-example.yml
    with:
      environment: ${{ inputs.environment }}
      message: ${{ inputs.message }}